import AuthProvider from "@/context/AuthProvider"
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/Navbar"
import { ThemeProvider } from "@/context/ThemeProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
    <html lang="en"  suppressHydrationWarning={true} >  
      <body className="min-h-screen">
      <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
        <Navbar></Navbar>
        {children}
        </ThemeProvider>
      <Toaster/>
      </body>
    </html>
    </AuthProvider>
  )
}
