import AuthProvider from "@/context/AuthProvider"
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
    <html lang="en">  
      <body>
        <Navbar></Navbar>
        {children}
      <Toaster/>
      </body>
    </html>
    </AuthProvider>
  )
}
