import AuthProvider from "@/context/AuthProvider"
import './globals.css'
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
      <body>{children}
      <Toaster/>
      </body>
      
      </AuthProvider>
    </html>
  )
}
